version: "3.8"

services:
  app:
    build: .
    ports:
      - "5003:5003"
    environment:
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DBNAME=transaction_db
      - USER_SERVICE_URL=http://user-service:5001
      - ARTICLE_SERVICE_URL=http://article-service:5002
      - PORT=5003
    depends_on:
      - mongodb
      - user-service
      - article-service

  user-service:
    image: user-service-image # Replace with the actual image or build context
    ports:
      - "5001:5001"
    environment:
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DBNAME=user_db
      - PORT=5001
    depends_on:
      - mongodb

  article-service:
    image: article-service-image # Replace with the actual image or build context
    ports:
      - "5002:5002"
    environment:
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DBNAME=article_db
      - PORT=5002
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
