version: "3.8"

services:
  app:
    build: .
    ports:
      - "5003:5003"
    environment:
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - PORT=5003
  mongodb:
    image: mongo
    ports:
      - "27018:27018"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
